steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'asia-northeast1-docker.pkg.dev/my-cloud-run01/foo1/my-python-app:$COMMIT_SHA', '.']
#    args: ['build', '-t', 'asia-northeast1-docker.pkg.dev/$PROJECT_ID/foo1/my-python-app:$COMMIT_SHA', '.']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'asia-northeast1-docker.pkg.dev/my-cloud-run01/foo1/my-python-app:$COMMIT_SHA']

  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'gcloud'
    args: ['run', 'deploy', 'stlit01app',
            '--image', 'asia-northeast1-docker.pkg.dev/my-cloud-run01/foo1/my-python-app:$COMMIT_SHA', 
            '--region', 'asia-northeast1',
            '--platform', 'managed',
            '--port', '8501',
            '--memory', '1G',
            '--max-instances', '3']

options:
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET
serviceAccount: github-delivery@my-cloud-run01.iam.gserviceaccount.com
