steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'asia-northeast1-docker.pkg.dev/$PROJECT_ID/foo1/my-python-app:$COMMIT_SHA', '.']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'asia-northeast1-docker.pkg.dev/$PROJECT_ID/foo1/my-python-app:$COMMIT_SHA']

  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'gcloud'
    args: ['run', 'deploy', 'stlit01app',
            '--image', 'gcr.io/asia-northeast1-docker.pkg.dev/$PROJECT_ID/my-python-app:$COMMIT_SHA',
            '--region', 'asia-northeast1',
            '--platform', 'managed',
            '--port', '8501',
            '--memory', '1G',
            '--max-instances', '3']

images:
  - 'gcr.io/$PROJECT_ID/my-python-app:$COMMIT_SHA'
serviceAccount: github-delivery@my-cloud-run01.iam.gserviceaccount.com
