name: Deploy to Cloud Run

on:
  push:
#    branches: [main]
    branches:
      - '*'
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build and push Docker image
        run: |
          docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/streamlit-app:${{ github.sha }} .
          docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/streamlit-app:${{ github.sha }}

      - name: Deploy to Cloud Run
        uses: google-github-actions/deploy-cloudrun@v1
        with:
          service: streamlit-app
          image: gcr.io/${{ secrets.GCP_PROJECT_ID }}/streamlit-app:${{ github.sha }}
          region:  asia-northeast1 # Cloud Run リージョンを指定
          # 必要に応じて、他の Cloud Run デプロイオプション (env vars, etc.) を追加
